import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import { Container, Stack, Box, Heading, Text, Button, Link, useColorModeValue } from '@chakra-ui/react';
import { GithubLogo, TwitterLogo } from 'phosphor-react';
import Footer from '../components/Footer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Linwood Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>

        <Container maxW={'3xl'}>
          <Stack
            as={Box}
            textAlign={'center'}
            spacing={{ base: 8, md: 14 }}
            py={{ base: 20, md: 36 }}>
            <Heading
              fontWeight={600}
              fontSize={{ base: '2xl', sm: '4xl', md: '6xl' }}
              lineHeight={'110%'}>
              Linwood{' '}
              <Text as={'span'} color={'green.400'}>
                Development
              </Text>
            </Heading>
            <Stack direction="row" justifyContent="center" spacing={3} alignItems="center">
              <Button colorScheme="green" size="lg">Projects</Button>
              <Button
                as={Link}
                _hover={{
                  textDecoration: 'none',
                  bg: useColorModeValue('gray.200', 'gray.700'),
                }}
                href={'#contact'} size="lg">Contact</Button>
            </Stack>
          </Stack>
        </Container>

        <Container maxW={'3xl'} id="contact">
          <Stack
            as={Box}
            textAlign={'center'}
            spacing={{ base: 8, md: 14 }}
            py={{ base: 20, md: 36 }}>
            <Heading
              fontWeight={600}
              as="h2"
              lineHeight={'110%'}>
              Contact
            </Heading>
            <Stack direction="row" justifyContent="center" spacing={3} alignItems="center">
              <Button colorScheme="green" size="lg" leftIcon={<GithubLogo size={24} />}>GitHub</Button>
              <Button colorScheme="teal" size="lg" leftIcon={<TwitterLogo size={24} />}>Twitter</Button>
            </Stack>
          </Stack>
        </Container>
      </main>
      <Footer />
    </div>
  )
}

export default Home
